name: Test Fluent Bit Parser

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-fluent-bit-parser:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # หยุด workflow หลัง 5 นาทีถ้ายังไม่จบ
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up directories and sample data
        run: |
          mkdir -p csv conf
          echo "No.,MACHINE_NO,Lot" > csv/sample.csv
          echo "1,CRST_109,A1816812508300130162" >> csv/sample.csv
          echo "2,CRST_109,A1816812508300130162" >> csv/sample.csv
          ls -l csv/ conf/ read_from_stdin.py || echo "Missing files"

      - name: Run Fluent Bit and Pipe to Python
        run: |
          docker run --rm -v $(pwd)/csv:/csv -v $(pwd)/conf:/conf fluent/fluent-bit:latest /fluent-bit/bin/fluent-bit -c /conf/fluent-bit.conf --once | python read_from_stdin.py